dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 64
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
  OFFICIAL_EPOCH_LENGTH: 20000 # number of images / batch size 
  num_workers: 24
student:
  arch: vit_small
  patch_size: 14
  drop_path_rate: 0
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  # arch: 'dinov2_vitl14'
  # embed_dim: 1024
  momentum_teacher: 0.994
optim:
  epochs: 10
  weight_decay_end: 0.2
  base_lr: 5.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 0
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
distill_cfg:
  teacher_arch: 'dinov2_vitl14'
  teacher_embed_dim: 1024

# distill teacher arch
# 'dinov2_vits14', embed_dim=   
# 'dinov2_vitb14', embed_dim=   
# 'dinov2_vitl14', embed_dim=
# 'dinov2_vitg14', embed_dim=   
# 'dinov2_vits14_reg'
# 'dinov2_vitb14_reg'
# 'dinov2_vitl14_reg'
# 'dinov2_vitg14_reg'
# /home/julian/.cache/torch/hub/facebookresearch_dinov2_main