dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
  koleo_loss_weight: 0.1
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 64
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
  OFFICIAL_EPOCH_LENGTH: 5000 # (number of images) 330000 / batch size
student:
  arch: vit_large
  patch_size: 32
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  # from ssl defualt config
  epochs: 100
  weight_decay: 0.04
  # weight_decay_end: 0.4
  # base_lr: 0.004  # learning rate for a batch size of 1024
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 0
  min_lr: 1.0e-07
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  # layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
  #
  weight_decay_end: 0.2
  base_lr: 2.0e-05  # learning rate for a batch size of 1024
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
  global_crops_size: 224